//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyrosoft.Medea.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gyrosoft.Medea.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Clinic&gt;.
        /// </summary>
        internal static string DefaultClinicName {
            get {
                return ResourceManager.GetString("DefaultClinicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded database engine could not close data file..
        /// </summary>
        internal static string ErrorEDBClose {
            get {
                return ResourceManager.GetString("ErrorEDBClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not commit changes..
        /// </summary>
        internal static string ErrorEDBCommit {
            get {
                return ResourceManager.GetString("ErrorEDBCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete object from database..
        /// </summary>
        internal static string ErrorEDBDelete {
            get {
                return ResourceManager.GetString("ErrorEDBDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified object does not exists in database..
        /// </summary>
        internal static string ErrorEDBIdentityNotFound {
            get {
                return ResourceManager.GetString("ErrorEDBIdentityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string is invalid..
        /// </summary>
        internal static string ErrorEDBInvalidConnectionString {
            get {
                return ResourceManager.GetString("ErrorEDBInvalidConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system could not find the specified path..
        /// </summary>
        internal static string ErrorEDBInvalidDirectory {
            get {
                return ResourceManager.GetString("ErrorEDBInvalidDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is not open..
        /// </summary>
        internal static string ErrorEDBNotOpen {
            get {
                return ResourceManager.GetString("ErrorEDBNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded database engine could not open data file..
        /// </summary>
        internal static string ErrorEDBOpen {
            get {
                return ResourceManager.GetString("ErrorEDBOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not rollback changes..
        /// </summary>
        internal static string ErrorEDBRollback {
            get {
                return ResourceManager.GetString("ErrorEDBRollback", resourceCulture);
            }
        }
    }
}
