//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyrosoft.Medea.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gyrosoft.Medea.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About {0}....
        /// </summary>
        internal static string ApplicationAboutMenuItemFmt {
            get {
                return ResourceManager.GetString("ApplicationAboutMenuItemFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string ApplicationFormCaptionFmt {
            get {
                return ResourceManager.GetString("ApplicationFormCaptionFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Version {2} {1}.
        /// </summary>
        internal static string ApplicationFormCaptionFmtWithVersion {
            get {
                return ResourceManager.GetString("ApplicationFormCaptionFmtWithVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medea.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap BitmapAddRecord_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapAddRecord_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapCamera_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapCamera_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapComment_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapComment_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapCurrentItem_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapCurrentItem_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapDial_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapDial_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapEditRecord_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapEditRecord_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapExamination_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapExamination_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapGoToNext_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapGoToNext_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapGoToPrevious_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapGoToPrevious_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapHelp_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapHelp_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapHome_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapHome_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapNavBack_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapNavBack_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapNavForward_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapNavForward_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapNone_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapNone_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapOptions_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapOptions_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapPause_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapPause_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapPicture_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapPicture_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapPictures_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapPictures_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapPlay_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapPlay_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapPrint_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapPrint_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapProgress_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapProgress_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapRefresh_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapRefresh_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapSave_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapSave_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapSplash_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapSplash_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapStop_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapStop_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BitmapTask_HighColor {
            get {
                object obj = ResourceManager.GetObject("BitmapTask_HighColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string ButtonChange {
            get {
                return ResourceManager.GetString("ButtonChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AzimuthPlus.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this entity?.
        /// </summary>
        internal static string ConfirmDeleteEntity {
            get {
                return ResourceManager.GetString("ConfirmDeleteEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &apos;{0}&apos;?.
        /// </summary>
        internal static string ConfirmDeleteItem {
            get {
                return ResourceManager.GetString("ConfirmDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} snapshots?.
        /// </summary>
        internal static string ConfirmDeleteSnapshots {
            get {
                return ResourceManager.GetString("ConfirmDeleteSnapshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &apos;{0}&apos; and all its descendants?.
        /// </summary>
        internal static string ConfirmDeleteTree {
            get {
                return ResourceManager.GetString("ConfirmDeleteTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save examination changes?.
        /// </summary>
        internal static string ConfirmSaveExamination {
            get {
                return ResourceManager.GetString("ConfirmSaveExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save patient file?.
        /// </summary>
        internal static string ConfirmSavePatient {
            get {
                return ResourceManager.GetString("ConfirmSavePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        internal static string EditionDemo {
            get {
                return ResourceManager.GetString("EditionDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise Edition.
        /// </summary>
        internal static string EditionEnterprise {
            get {
                return ResourceManager.GetString("EditionEnterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Edition.
        /// </summary>
        internal static string EditionPersonal {
            get {
                return ResourceManager.GetString("EditionPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create new indication category..
        /// </summary>
        internal static string ErrorCreateIndicationCategory {
            get {
                return ResourceManager.GetString("ErrorCreateIndicationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create new indication definition..
        /// </summary>
        internal static string ErrorCreateIndicationDefinition {
            get {
                return ResourceManager.GetString("ErrorCreateIndicationDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete entity linked by another entities..
        /// </summary>
        internal static string ErrorDeleteEntity {
            get {
                return ResourceManager.GetString("ErrorDeleteEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity name cannot be blank or consist of whitespace only..
        /// </summary>
        internal static string ErrorEmptyName {
            get {
                return ResourceManager.GetString("ErrorEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination validation failed:.
        /// </summary>
        internal static string ErrorExaminationValidation {
            get {
                return ResourceManager.GetString("ErrorExaminationValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid examination kind..
        /// </summary>
        internal static string ErrorExaminationValidationKind {
            get {
                return ResourceManager.GetString("ErrorExaminationValidationKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid patient..
        /// </summary>
        internal static string ErrorExaminationValidationPatient {
            get {
                return ResourceManager.GetString("ErrorExaminationValidationPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid physician..
        /// </summary>
        internal static string ErrorExaminationValidationPhysician {
            get {
                return ResourceManager.GetString("ErrorExaminationValidationPhysician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM Error 0x{0:X}..
        /// </summary>
        internal static string ErrorHResult {
            get {
                return ResourceManager.GetString("ErrorHResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improper configuration. Please reinstall the application..
        /// </summary>
        internal static string ErrorImproperConfiguration {
            get {
                return ResourceManager.GetString("ErrorImproperConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indication &apos;{0}&apos; is in use..
        /// </summary>
        internal static string ErrorIndicationUsed {
            get {
                return ResourceManager.GetString("ErrorIndicationUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified name is invalid..
        /// </summary>
        internal static string ErrorInvalidName {
            get {
                return ResourceManager.GetString("ErrorInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save data..
        /// </summary>
        internal static string ErrorSaveData {
            get {
                return ResourceManager.GetString("ErrorSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not display option page..
        /// </summary>
        internal static string ErrorShowOptionPage {
            get {
                return ResourceManager.GetString("ErrorShowOptionPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find device &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorVMBadDeviceName {
            get {
                return ResourceManager.GetString("ErrorVMBadDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectX version 8.1 or later is not installed..
        /// </summary>
        internal static string ErrorVMBadDirectXVersion {
            get {
                return ResourceManager.GetString("ErrorVMBadDirectXVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid grabber media format..
        /// </summary>
        internal static string ErrorVMBadGrabberMediaFormat {
            get {
                return ResourceManager.GetString("ErrorVMBadGrabberMediaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not grab picture..
        /// </summary>
        internal static string ErrorVMCantGrab {
            get {
                return ResourceManager.GetString("ErrorVMCantGrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified window is unable to display video stream..
        /// </summary>
        internal static string ErrorVMInvalidVideoWindow {
            get {
                return ResourceManager.GetString("ErrorVMInvalidVideoWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectShow FilterGraph is not installed..
        /// </summary>
        internal static string ErrorVMNoFilterGraph {
            get {
                return ResourceManager.GetString("ErrorVMNoFilterGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectShow SampleGrabber is not installed..
        /// </summary>
        internal static string ErrorVMNoSampleGrabber {
            get {
                return ResourceManager.GetString("ErrorVMNoSampleGrabber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No video input device selected..
        /// </summary>
        internal static string ErrorVMNoVideoInputDevice {
            get {
                return ResourceManager.GetString("ErrorVMNoVideoInputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide image collection.
        /// </summary>
        internal static string ImagingCollectionHide {
            get {
                return ResourceManager.GetString("ImagingCollectionHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show image collection.
        /// </summary>
        internal static string ImagingCollectionShow {
            get {
                return ResourceManager.GetString("ImagingCollectionShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} snapshot(s).
        /// </summary>
        internal static string ImagingSnapshotCount {
            get {
                return ResourceManager.GetString("ImagingSnapshotCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating thumbnails ({0}% done)....
        /// </summary>
        internal static string ImagingThumbnailsUpdating {
            get {
                return ResourceManager.GetString("ImagingThumbnailsUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture {0}, {1}x{2}.
        /// </summary>
        internal static string InfoCapture {
            get {
                return ResourceManager.GetString("InfoCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot {0}x{1}.
        /// </summary>
        internal static string InfoSnapshot {
            get {
                return ResourceManager.GetString("InfoSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string NavBack {
            get {
                return ResourceManager.GetString("NavBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to {0}.
        /// </summary>
        internal static string NavBackFmt {
            get {
                return ResourceManager.GetString("NavBackFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string NavForward {
            get {
                return ResourceManager.GetString("NavForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward to {0}.
        /// </summary>
        internal static string NavForwardFmt {
            get {
                return ResourceManager.GetString("NavForwardFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string NavHistoryTitle {
            get {
                return ResourceManager.GetString("NavHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New category.
        /// </summary>
        internal static string NewIndicationCategory {
            get {
                return ResourceManager.GetString("NewIndicationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New indication definition.
        /// </summary>
        internal static string NewIndicationDefinition {
            get {
                return ResourceManager.GetString("NewIndicationDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string OptionPageGeneral {
            get {
                return ResourceManager.GetString("OptionPageGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string OptionPageVideo {
            get {
                return ResourceManager.GetString("OptionPageVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date:.
        /// </summary>
        internal static string RepBirthdate {
            get {
                return ResourceManager.GetString("RepBirthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conclusion.
        /// </summary>
        internal static string RepConclusion {
            get {
                return ResourceManager.GetString("RepConclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination date:.
        /// </summary>
        internal static string RepExaminationDate {
            get {
                return ResourceManager.GetString("RepExaminationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination kind:.
        /// </summary>
        internal static string RepExaminationKind {
            get {
                return ResourceManager.GetString("RepExaminationKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string RepGenderFemale {
            get {
                return ResourceManager.GetString("RepGenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string RepGenderMale {
            get {
                return ResourceManager.GetString("RepGenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indications.
        /// </summary>
        internal static string RepIndications {
            get {
                return ResourceManager.GetString("RepIndications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No conclusion entered..
        /// </summary>
        internal static string RepNoConclusion {
            get {
                return ResourceManager.GetString("RepNoConclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No indications..
        /// </summary>
        internal static string RepNoIndications {
            get {
                return ResourceManager.GetString("RepNoIndications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient:.
        /// </summary>
        internal static string RepPatient {
            get {
                return ResourceManager.GetString("RepPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physician.
        /// </summary>
        internal static string RepPhysician {
            get {
                return ResourceManager.GetString("RepPhysician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;_____&quot;____________20____.
        /// </summary>
        internal static string RepSignDate {
            get {
                return ResourceManager.GetString("RepSignDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examinations.
        /// </summary>
        internal static string RollExamination {
            get {
                return ResourceManager.GetString("RollExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination kind.
        /// </summary>
        internal static string RollExaminationKind {
            get {
                return ResourceManager.GetString("RollExaminationKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination kind.
        /// </summary>
        internal static string RollExaminationKind_ {
            get {
                return ResourceManager.GetString("RollExaminationKind_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string RollExaminationPatient {
            get {
                return ResourceManager.GetString("RollExaminationPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform date.
        /// </summary>
        internal static string RollExaminationPerformDate {
            get {
                return ResourceManager.GetString("RollExaminationPerformDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string RollNamedEntityName {
            get {
                return ResourceManager.GetString("RollNamedEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        internal static string RollPatient {
            get {
                return ResourceManager.GetString("RollPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        internal static string RollPatientBirthDate {
            get {
                return ResourceManager.GetString("RollPatientBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name.
        /// </summary>
        internal static string RollPatientFamilyName {
            get {
                return ResourceManager.GetString("RollPatientFamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string RollPatientFirstName {
            get {
                return ResourceManager.GetString("RollPatientFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        internal static string RollPatientMiddleName {
            get {
                return ResourceManager.GetString("RollPatientMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physicians.
        /// </summary>
        internal static string RollPhysician {
            get {
                return ResourceManager.GetString("RollPhysician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating report....
        /// </summary>
        internal static string StatusCreateReport {
            get {
                return ResourceManager.GetString("StatusCreateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting item(s)....
        /// </summary>
        internal static string StatusDeleting {
            get {
                return ResourceManager.GetString("StatusDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string StatusLoading {
            get {
                return ResourceManager.GetString("StatusLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading configuration....
        /// </summary>
        internal static string StatusLoadingConfig {
            get {
                return ResourceManager.GetString("StatusLoadingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data....
        /// </summary>
        internal static string StatusLoadingData {
            get {
                return ResourceManager.GetString("StatusLoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to database....
        /// </summary>
        internal static string StatusOpenDatabase {
            get {
                return ResourceManager.GetString("StatusOpenDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening view....
        /// </summary>
        internal static string StatusOpenView {
            get {
                return ResourceManager.GetString("StatusOpenView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving data....
        /// </summary>
        internal static string StatusSavingData {
            get {
                return ResourceManager.GetString("StatusSavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down....
        /// </summary>
        internal static string StatusShutdown {
            get {
                return ResourceManager.GetString("StatusShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving snapshot....
        /// </summary>
        internal static string StatusSnapshot {
            get {
                return ResourceManager.GetString("StatusSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string TaskGroupCreate {
            get {
                return ResourceManager.GetString("TaskGroupCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string TaskGroupSearch {
            get {
                return ResourceManager.GetString("TaskGroupSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Examination.
        /// </summary>
        internal static string TaskNewExamination {
            get {
                return ResourceManager.GetString("TaskNewExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Patient.
        /// </summary>
        internal static string TaskNewPatient {
            get {
                return ResourceManager.GetString("TaskNewPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        internal static string TaskPatients {
            get {
                return ResourceManager.GetString("TaskPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination.
        /// </summary>
        internal static string ViewExamination {
            get {
                return ResourceManager.GetString("ViewExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string ViewImaging {
            get {
                return ResourceManager.GetString("ViewImaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string ViewPatient {
            get {
                return ResourceManager.GetString("ViewPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll.
        /// </summary>
        internal static string ViewRoll {
            get {
                return ResourceManager.GetString("ViewRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Pad.
        /// </summary>
        internal static string ViewTaskPad {
            get {
                return ResourceManager.GetString("ViewTaskPad", resourceCulture);
            }
        }
    }
}
